name: AcadeFella-BackendService

on:
  push:
    branches: [ main ]

jobs:
  build-and-unit-test:
    name: Build & tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11.0.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Verify code formatting
        run: ./go verify_format
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: ./go build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar
          retention-days: 1
          if-no-files-found: error
      - name: Upload Unit test and Jacoco Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Tests and Jacoco Reports
          path: build/reports/
          retention-days: 5

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11.0.8
      - name: Run Integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: ./go clean integrationTest
      - name: Upload Integration test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Tests and Jacoco Reports
          path: build/reports/
          retention-days: 5

  docker-build:
    needs: [ build-and-unit-test, integration-test ]
    name: Dockerize & deploy nonlive
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        env:
          DOCKER_FILE: Dockerfile
